<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

   <ItemGroup>
    <Compile Include="..\_shared\PostgreSqlConsumerSupport.cs" Link="PostgreSqlConsumerSupport.cs" />
  </ItemGroup>

 <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SmartPipe.Core" />
    <PackageReference Include="SmartPipe.Extensions.EntityFrameworkCore" />
    <PackageReference Include="SmartPipe.Extensions.PostgreSql" />
  </ItemGroup>
</Project>
