<Project>
  <PropertyGroup>
    <Authors>SmartPipe</Authors>
    <IsPackable>true</IsPackable>
    <Copyright>Copyright (c) SmartPipe 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/MrFr3di/SmartPipe-Core</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/MrFr3di/SmartPipe-Core</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
    <PathMap>$(SmartPipeRepositoryRoot)=/_/</PathMap>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnablePackageValidation>true</EnablePackageValidation>
    <ApiCompatEnableRuleCannotChangeParameterName>true</ApiCompatEnableRuleCannotChangeParameterName>
    <EnableStrictModeForCompatibleTfms>true</EnableStrictModeForCompatibleTfms>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
</Project>
