<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SmartPipe.Perf.DependencyInjection.V212</AssemblyName>
    <RootNamespace>SmartPipe.Perf.DependencyInjection</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../SmartPipe.Perf.DependencyInjection.Shared/*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="DependencyInjectionTarget.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="SmartPipe.Extensions" Version="2.1.2" />
  </ItemGroup>
</Project>
